	.align 2
DirectSoundWaveData_08124C18::
	.incbin "sound/direct_sound_samples/08124C18.bin"

	.align 2
DirectSoundWaveData_0813C744::
	.incbin "sound/direct_sound_samples/0813C744.bin"

	.align 2
DirectSoundWaveData_08147114::
	.incbin "sound/direct_sound_samples/08147114.bin"

	.align 2
DirectSoundWaveData_0814E1F8::
	.incbin "sound/direct_sound_samples/0814E1F8.bin"

	.align 2
DirectSoundWaveData_08154EB8::
	.incbin "sound/direct_sound_samples/08154EB8.bin"

	.align 2
DirectSoundWaveData_0816E5CC::
	.incbin "sound/direct_sound_samples/0816E5CC.bin"

	.align 2
DirectSoundWaveData_0817472C::
	.incbin "sound/direct_sound_samples/0817472C.bin"

	.align 2
DirectSoundWaveData_081748EC::
	.incbin "sound/direct_sound_samples/081748EC.bin"

	.align 2
DirectSoundWaveData_0818CE50::
	.incbin "sound/direct_sound_samples/0818CE50.bin"

	.align 2
DirectSoundWaveData_0818DD4C::
	.incbin "sound/direct_sound_samples/0818DD4C.bin"

	.align 2
DirectSoundWaveData_08197EF0::
	.incbin "sound/direct_sound_samples/08197EF0.bin"

	.align 2
DirectSoundWaveData_081A841C::
	.incbin "sound/direct_sound_samples/081A841C.bin"

	.align 2
DirectSoundWaveData_081AA998::
	.incbin "sound/direct_sound_samples/081AA998.bin"

	.align 2
DirectSoundWaveData_081AB314::
	.incbin "sound/direct_sound_samples/081AB314.bin"

	.align 2
DirectSoundWaveData_081ABAE4::
	.incbin "sound/direct_sound_samples/081ABAE4.bin"

	.align 2
DirectSoundWaveData_081AF364::
	.incbin "sound/direct_sound_samples/081AF364.bin"

	.align 2
DirectSoundWaveData_081B1084::
	.incbin "sound/direct_sound_samples/081B1084.bin"

	.align 2
DirectSoundWaveData_081B57D8::
	.incbin "sound/direct_sound_samples/081B57D8.bin"

	.align 2
DirectSoundWaveData_081C2AEC::
	.incbin "sound/direct_sound_samples/081C2AEC.bin"

	.align 2
DirectSoundWaveData_081C4570::
	.incbin "sound/direct_sound_samples/081C4570.bin"

	.align 2
DirectSoundWaveData_081D3F44::
	.incbin "sound/direct_sound_samples/081D3F44.bin"

	.align 2
DirectSoundWaveData_081E38E0::
	.incbin "sound/direct_sound_samples/081E38E0.bin"

	.align 2
DirectSoundWaveData_081E80D8::
	.incbin "sound/direct_sound_samples/081E80D8.bin"

	.align 2
DirectSoundWaveData_081EE0C0::
	.incbin "sound/direct_sound_samples/081EE0C0.bin"

	.align 2
DirectSoundWaveData_081F1120::
	.incbin "sound/direct_sound_samples/081F1120.bin"

	.align 2
DirectSoundWaveData_081F7064::
	.incbin "sound/direct_sound_samples/081F7064.bin"

	.align 2
DirectSoundWaveData_08204AD0::
	.incbin "sound/direct_sound_samples/08204AD0.bin"

	.align 2
DirectSoundWaveData_082081D4::
	.incbin "sound/direct_sound_samples/082081D4.bin"

	.align 2
DirectSoundWaveData_0820FD14::
	.incbin "sound/direct_sound_samples/0820FD14.bin"

	.align 2
DirectSoundWaveData_0821763C::
	.incbin "sound/direct_sound_samples/0821763C.bin"

	.align 2
DirectSoundWaveData_0821B8F0::
	.incbin "sound/direct_sound_samples/0821B8F0.bin"

	.align 2
DirectSoundWaveData_0821F104::
	.incbin "sound/direct_sound_samples/0821F104.bin"

	.align 2
DirectSoundWaveData_08226C28::
	.incbin "sound/direct_sound_samples/08226C28.bin"

	.align 2
DirectSoundWaveData_0822F894::
	.incbin "sound/direct_sound_samples/0822F894.bin"

	.align 2
DirectSoundWaveData_082358F4::
	.incbin "sound/direct_sound_samples/082358F4.bin"

	.align 2
DirectSoundWaveData_08243C08::
	.incbin "sound/direct_sound_samples/08243C08.bin"

	.align 2
DirectSoundWaveData_0825721C::
	.incbin "sound/direct_sound_samples/0825721C.bin"

	.align 2
DirectSoundWaveData_08261EEC::
	.incbin "sound/direct_sound_samples/08261EEC.bin"

	.align 2
DirectSoundWaveData_08271370::
	.incbin "sound/direct_sound_samples/08271370.bin"

	.align 2
DirectSoundWaveData_0828264C::
	.incbin "sound/direct_sound_samples/0828264C.bin"

	.align 2
DirectSoundWaveData_0828B260::
	.incbin "sound/direct_sound_samples/0828B260.bin"

	.align 2
DirectSoundWaveData_0828E0D4::
	.incbin "sound/direct_sound_samples/0828E0D4.bin"

	.align 2
DirectSoundWaveData_0829517C::
	.incbin "sound/direct_sound_samples/0829517C.bin"

	.align 2
DirectSoundWaveData_08297F94::
	.incbin "sound/direct_sound_samples/08297F94.bin"

	.align 2
DirectSoundWaveData_0829A1E0::
	.incbin "sound/direct_sound_samples/0829A1E0.bin"

	.align 2
DirectSoundWaveData_0829DA04::
	.incbin "sound/direct_sound_samples/0829DA04.bin"

	.align 2
DirectSoundWaveData_0829FC50::
	.incbin "sound/direct_sound_samples/0829FC50.bin"

	.align 2
DirectSoundWaveData_082B01E4::
	.incbin "sound/direct_sound_samples/082B01E4.bin"

	.align 2
DirectSoundWaveData_082C6AFC::
	.incbin "sound/direct_sound_samples/082C6AFC.bin"

	.align 2
DirectSoundWaveData_082D43A4::
	.incbin "sound/direct_sound_samples/082D43A4.bin"

	.align 2
DirectSoundWaveData_082D65EC::
	.incbin "sound/direct_sound_samples/082D65EC.bin"

	.align 2
DirectSoundWaveData_082E61D8::
	.incbin "sound/direct_sound_samples/082E61D8.bin"

	.align 2
DirectSoundWaveData_082ED1BC::
	.incbin "sound/direct_sound_samples/082ED1BC.bin"

	.align 2
DirectSoundWaveData_082F7920::
	.incbin "sound/direct_sound_samples/082F7920.bin"

	.align 2
DirectSoundWaveData_082FF07C::
	.incbin "sound/direct_sound_samples/082FF07C.bin"

	.align 2
DirectSoundWaveData_08302F00::
	.incbin "sound/direct_sound_samples/08302F00.bin"

	.align 2
DirectSoundWaveData_08330CA8::
	.incbin "sound/direct_sound_samples/08330CA8.bin"

	.align 2
DirectSoundWaveData_08332F18::
	.incbin "sound/direct_sound_samples/08332F18.bin"

	.align 2
DirectSoundWaveData_0835D948::
	.incbin "sound/direct_sound_samples/0835D948.bin"

	.align 2
DirectSoundWaveData_0837B9D4::
	.incbin "sound/direct_sound_samples/0837B9D4.bin"

	.align 2
DirectSoundWaveData_0837E488::
	.incbin "sound/direct_sound_samples/0837E488.bin"

	.align 2
DirectSoundWaveData_08380CDC::
	.incbin "sound/direct_sound_samples/08380CDC.bin"

	.align 2
DirectSoundWaveData_08385BD0::
	.incbin "sound/direct_sound_samples/08385BD0.bin"

	.align 2
DirectSoundWaveData_0838D6FC::
	.incbin "sound/direct_sound_samples/0838D6FC.bin"

	.align 2
DirectSoundWaveData_08390ECC::
	.incbin "sound/direct_sound_samples/08390ECC.bin"

	.align 2
DirectSoundWaveData_083B4300::
	.incbin "sound/direct_sound_samples/083B4300.bin"

	.align 2
DirectSoundWaveData_083C67E0::
	.incbin "sound/direct_sound_samples/083C67E0.bin"

	.align 2
DirectSoundWaveData_083DA2F4::
	.incbin "sound/direct_sound_samples/083DA2F4.bin"

	.align 2
DirectSoundWaveData_083DDFFC::
	.incbin "sound/direct_sound_samples/083DDFFC.bin"

	.align 2
DirectSoundWaveData_083EC940::
	.incbin "sound/direct_sound_samples/083EC940.bin"

	.align 2
DirectSoundWaveData_083F0A90::
	.incbin "sound/direct_sound_samples/083F0A90.bin"

	.align 2
DirectSoundWaveData_083F1BA8::
	.incbin "sound/direct_sound_samples/083F1BA8.bin"

	.align 2
DirectSoundWaveData_083F4CF8::
	.incbin "sound/direct_sound_samples/083F4CF8.bin"

	.align 2
DirectSoundWaveData_083FA570::
	.incbin "sound/direct_sound_samples/083FA570.bin"

	.align 2
DirectSoundWaveData_08400370::
	.incbin "sound/direct_sound_samples/08400370.bin"

	.align 2
DirectSoundWaveData_08404260::
	.incbin "sound/direct_sound_samples/08404260.bin"

	.align 2
DirectSoundWaveData_08416F74::
	.incbin "sound/direct_sound_samples/08416F74.bin"

	.align 2
DirectSoundWaveData_08420D04::
	.incbin "sound/direct_sound_samples/08420D04.bin"

	.align 2
DirectSoundWaveData_08421914::
	.incbin "sound/direct_sound_samples/08421914.bin"

	.align 2
DirectSoundWaveData_08422C38::
	.incbin "sound/direct_sound_samples/08422C38.bin"

	.align 2
DirectSoundWaveData_08425024::
	.incbin "sound/direct_sound_samples/08425024.bin"

	.align 2
DirectSoundWaveData_08428C40::
	.incbin "sound/direct_sound_samples/08428C40.bin"

	.align 2
DirectSoundWaveData_0842ABC4::
	.incbin "sound/direct_sound_samples/0842ABC4.bin"

	.align 2
DirectSoundWaveData_08439044::
	.incbin "sound/direct_sound_samples/08439044.bin"

	.align 2
DirectSoundWaveData_08448298::
	.incbin "sound/direct_sound_samples/08448298.bin"

	.align 2
DirectSoundWaveData_0844A91C::
	.incbin "sound/direct_sound_samples/0844A91C.bin"

	.align 2
DirectSoundWaveData_0844AB94::
	.incbin "sound/direct_sound_samples/0844AB94.bin"

	.align 2
DirectSoundWaveData_0844C40C::
	.incbin "sound/direct_sound_samples/0844C40C.bin"

	.align 2
DirectSoundWaveData_0844E2D0::
	.incbin "sound/direct_sound_samples/0844E2D0.bin"

	.align 2
DirectSoundWaveData_08450AA4::
	.incbin "sound/direct_sound_samples/08450AA4.bin"

	.align 2
DirectSoundWaveData_08451B84::
	.incbin "sound/direct_sound_samples/08451B84.bin"

	.align 2
DirectSoundWaveData_08452D50::
	.incbin "sound/direct_sound_samples/08452D50.bin"

	.align 2
DirectSoundWaveData_08454584::
	.incbin "sound/direct_sound_samples/08454584.bin"

	.align 2
DirectSoundWaveData_08456018::
	.incbin "sound/direct_sound_samples/08456018.bin"

	.align 2
DirectSoundWaveData_0846CB64::
	.incbin "sound/direct_sound_samples/0846CB64.bin"

	.align 2
DirectSoundWaveData_08470A7C::
	.incbin "sound/direct_sound_samples/08470A7C.bin"

	.align 2
DirectSoundWaveData_08471478::
	.incbin "sound/direct_sound_samples/08471478.bin"

	.align 2
DirectSoundWaveData_08472EDC::
	.incbin "sound/direct_sound_samples/08472EDC.bin"

	.align 2
DirectSoundWaveData_084733E4::
	.incbin "sound/direct_sound_samples/084733E4.bin"

	.align 2
DirectSoundWaveData_08474558::
	.incbin "sound/direct_sound_samples/08474558.bin"

	.align 2
DirectSoundWaveData_08475CFC::
	.incbin "sound/direct_sound_samples/08475CFC.bin"

	.align 2
DirectSoundWaveData_08478D50::
	.incbin "sound/direct_sound_samples/08478D50.bin"

	.align 2
DirectSoundWaveData_084860E4::
	.incbin "sound/direct_sound_samples/084860E4.bin"

	.align 2
DirectSoundWaveData_0848B658::
	.incbin "sound/direct_sound_samples/0848B658.bin"

	.align 2
DirectSoundWaveData_0848D654::
	.incbin "sound/direct_sound_samples/0848D654.bin"

	.align 2
DirectSoundWaveData_0849AE18::
	.incbin "sound/direct_sound_samples/0849AE18.bin"

	.align 2
DirectSoundWaveData_0849B080::
	.incbin "sound/direct_sound_samples/0849B080.bin"

	.align 2
DirectSoundWaveData_0849D2E8::
	.incbin "sound/direct_sound_samples/0849D2E8.bin"

	.align 2
DirectSoundWaveData_0849E26C::
	.incbin "sound/direct_sound_samples/0849E26C.bin"

	.align 2
DirectSoundWaveData_0849F0F0::
	.incbin "sound/direct_sound_samples/0849F0F0.bin"

	.align 2
DirectSoundWaveData_0849F754::
	.incbin "sound/direct_sound_samples/0849F754.bin"

	.align 2
DirectSoundWaveData_084A1278::
	.incbin "sound/direct_sound_samples/084A1278.bin"

	.align 2
DirectSoundWaveData_084A18F0::
	.incbin "sound/direct_sound_samples/084A18F0.bin"

	.align 2
DirectSoundWaveData_084A1DEC::
	.incbin "sound/direct_sound_samples/084A1DEC.bin"

	.align 2
DirectSoundWaveData_084A42A0::
	.incbin "sound/direct_sound_samples/084A42A0.bin"

	.align 2
DirectSoundWaveData_084A9F74::
	.incbin "sound/direct_sound_samples/084A9F74.bin"

	.align 2
DirectSoundWaveData_084ACE08::
	.incbin "sound/direct_sound_samples/084ACE08.bin"

	.align 2
DirectSoundWaveData_084B227C::
	.incbin "sound/direct_sound_samples/084B227C.bin"

	.align 2
DirectSoundWaveData_084B5B40::
	.incbin "sound/direct_sound_samples/084B5B40.bin"

	.align 2
DirectSoundWaveData_084B63A8::
	.incbin "sound/direct_sound_samples/084B63A8.bin"

	.align 2
DirectSoundWaveData_084B820C::
	.incbin "sound/direct_sound_samples/084B820C.bin"

	.align 2
DirectSoundWaveData_084BD800::
	.incbin "sound/direct_sound_samples/084BD800.bin"

	.align 2
DirectSoundWaveData_084C2D54::
	.incbin "sound/direct_sound_samples/084C2D54.bin"

	.align 2
DirectSoundWaveData_084C30BC::
	.incbin "sound/direct_sound_samples/084C30BC.bin"

	.align 2
DirectSoundWaveData_084C5DA0::
	.incbin "sound/direct_sound_samples/084C5DA0.bin"

	.align 2
DirectSoundWaveData_084C8000::
	.incbin "sound/direct_sound_samples/084C8000.bin"

	.align 2
DirectSoundWaveData_084C91A4::
	.incbin "sound/direct_sound_samples/084C91A4.bin"

	.align 2
DirectSoundWaveData_084C985C::
	.incbin "sound/direct_sound_samples/084C985C.bin"

	.align 2
DirectSoundWaveData_084CA1C0::
	.incbin "sound/direct_sound_samples/084CA1C0.bin"

	.align 2
DirectSoundWaveData_084CBA38::
	.incbin "sound/direct_sound_samples/084CBA38.bin"

	.align 2
DirectSoundWaveData_084CDA6C::
	.incbin "sound/direct_sound_samples/084CDA6C.bin"

	.align 2
DirectSoundWaveData_084CF9D0::
	.incbin "sound/direct_sound_samples/084CF9D0.bin"

	.align 2
DirectSoundWaveData_084D00C8::
	.incbin "sound/direct_sound_samples/084D00C8.bin"

	.align 2
DirectSoundWaveData_084D094C::
	.incbin "sound/direct_sound_samples/084D094C.bin"

	.align 2
DirectSoundWaveData_084D12C4::
	.incbin "sound/direct_sound_samples/084D12C4.bin"

	.align 2
DirectSoundWaveData_084D1620::
	.incbin "sound/direct_sound_samples/084D1620.bin"

	.align 2
DirectSoundWaveData_084D3888::
	.incbin "sound/direct_sound_samples/084D3888.bin"

	.align 2
DirectSoundWaveData_084D4B28::
	.incbin "sound/direct_sound_samples/084D4B28.bin"

	.align 2
DirectSoundWaveData_084D4E08::
	.incbin "sound/direct_sound_samples/084D4E08.bin"

	.align 2
DirectSoundWaveData_084D5F2C::
	.incbin "sound/direct_sound_samples/084D5F2C.bin"

	.align 2
DirectSoundWaveData_084D6288::
	.incbin "sound/direct_sound_samples/084D6288.bin"

	.align 2
DirectSoundWaveData_084D8350::
	.incbin "sound/direct_sound_samples/084D8350.bin"

	.align 2
DirectSoundWaveData_084D959C::
	.incbin "sound/direct_sound_samples/084D959C.bin"

	.align 2
DirectSoundWaveData_084DB68C::
	.incbin "sound/direct_sound_samples/084DB68C.bin"

	.align 2
DirectSoundWaveData_084DC92C::
	.incbin "sound/direct_sound_samples/084DC92C.bin"

	.align 2
DirectSoundWaveData_084DCE2C::
	.incbin "sound/direct_sound_samples/084DCE2C.bin"

	.align 2
DirectSoundWaveData_084DF4B0::
	.incbin "sound/direct_sound_samples/084DF4B0.bin"

	.align 2
DirectSoundWaveData_084DF798::
	.incbin "sound/direct_sound_samples/084DF798.bin"

	.align 2
DirectSoundWaveData_084E1788::
	.incbin "sound/direct_sound_samples/084E1788.bin"

	.align 2
DirectSoundWaveData_084E9184::
	.incbin "sound/direct_sound_samples/084E9184.bin"

	.align 2
DirectSoundWaveData_084E97FC::
	.incbin "sound/direct_sound_samples/084E97FC.bin"

	.align 2
DirectSoundWaveData_084E9DAC::
	.incbin "sound/direct_sound_samples/084E9DAC.bin"

	.align 2
DirectSoundWaveData_084EA5B0::
	.incbin "sound/direct_sound_samples/084EA5B0.bin"

	.align 2
DirectSoundWaveData_084EABB0::
	.incbin "sound/direct_sound_samples/084EABB0.bin"

	.align 2
DirectSoundWaveData_084EB6B0::
	.incbin "sound/direct_sound_samples/084EB6B0.bin"

	.align 2
DirectSoundWaveData_084EBDAC::
	.incbin "sound/direct_sound_samples/084EBDAC.bin"

	.align 2
DirectSoundWaveData_084EC25C::
	.incbin "sound/direct_sound_samples/084EC25C.bin"

	.align 2
DirectSoundWaveData_084ECE44::
	.incbin "sound/direct_sound_samples/084ECE44.bin"

	.align 2
DirectSoundWaveData_084ED7C8::
	.incbin "sound/direct_sound_samples/084ED7C8.bin"

	.align 2
DirectSoundWaveData_084EE1B8::
	.incbin "sound/direct_sound_samples/084EE1B8.bin"

	.align 2
DirectSoundWaveData_084EF4EC::
	.incbin "sound/direct_sound_samples/084EF4EC.bin"

	.align 2
DirectSoundWaveData_084EF9FC::
	.incbin "sound/direct_sound_samples/084EF9FC.bin"

	.align 2
DirectSoundWaveData_084F04BC::
	.incbin "sound/direct_sound_samples/084F04BC.bin"

	.align 2
DirectSoundWaveData_084F18BC::
	.incbin "sound/direct_sound_samples/084F18BC.bin"

	.align 2
DirectSoundWaveData_084F2138::
	.incbin "sound/direct_sound_samples/084F2138.bin"

	.align 2
DirectSoundWaveData_084F3100::
	.incbin "sound/direct_sound_samples/084F3100.bin"

	.align 2
DirectSoundWaveData_084F464C::
	.incbin "sound/direct_sound_samples/084F464C.bin"

	.align 2
DirectSoundWaveData_084F4D18::
	.incbin "sound/direct_sound_samples/084F4D18.bin"

	.align 2
DirectSoundWaveData_084F5AE8::
	.incbin "sound/direct_sound_samples/084F5AE8.bin"

	.align 2
DirectSoundWaveData_084F5F60::
	.incbin "sound/direct_sound_samples/084F5F60.bin"

	.align 2
DirectSoundWaveData_084F7788::
	.incbin "sound/direct_sound_samples/084F7788.bin"

	.align 2
DirectSoundWaveData_084F904C::
	.incbin "sound/direct_sound_samples/084F904C.bin"

	.align 2
DirectSoundWaveData_084F9370::
	.incbin "sound/direct_sound_samples/084F9370.bin"

	.align 2
DirectSoundWaveData_084FA950::
	.incbin "sound/direct_sound_samples/084FA950.bin"

	.align 2
DirectSoundWaveData_084FB41C::
	.incbin "sound/direct_sound_samples/084FB41C.bin"

	.align 2
DirectSoundWaveData_084FBA94::
	.incbin "sound/direct_sound_samples/084FBA94.bin"

	.align 2
DirectSoundWaveData_084FBD3C::
	.incbin "sound/direct_sound_samples/084FBD3C.bin"

	.align 2
DirectSoundWaveData_084FD7AC::
	.incbin "sound/direct_sound_samples/084FD7AC.bin"

	.align 2
DirectSoundWaveData_085007F4::
	.incbin "sound/direct_sound_samples/085007F4.bin"

	.align 2
DirectSoundWaveData_0850394C::
	.incbin "sound/direct_sound_samples/0850394C.bin"

	.align 2
DirectSoundWaveData_0850675C::
	.incbin "sound/direct_sound_samples/0850675C.bin"

	.align 2
DirectSoundWaveData_085092CC::
	.incbin "sound/direct_sound_samples/085092CC.bin"

	.align 2
DirectSoundWaveData_08515438::
	.incbin "sound/direct_sound_samples/08515438.bin"

	.align 2
DirectSoundWaveData_0851F028::
	.incbin "sound/direct_sound_samples/0851F028.bin"

	.align 2
DirectSoundWaveData_085292BC::
	.incbin "sound/direct_sound_samples/085292BC.bin"

	.align 2
DirectSoundWaveData_08531084::
	.incbin "sound/direct_sound_samples/08531084.bin"

	.align 2
DirectSoundWaveData_08537AF8::
	.incbin "sound/direct_sound_samples/08537AF8.bin"

	.align 2
DirectSoundWaveData_0853D880::
	.incbin "sound/direct_sound_samples/0853D880.bin"

	.align 2
DirectSoundWaveData_08544BF4::
	.incbin "sound/direct_sound_samples/08544BF4.bin"

	.align 2
DirectSoundWaveData_0854DCDC::
	.incbin "sound/direct_sound_samples/0854DCDC.bin"

	.align 2
DirectSoundWaveData_08553550::
	.incbin "sound/direct_sound_samples/08553550.bin"

	.align 2
DirectSoundWaveData_085566B4::
	.incbin "sound/direct_sound_samples/085566B4.bin"

	.align 2
DirectSoundWaveData_08566E14::
	.incbin "sound/direct_sound_samples/08566E14.bin"

	.align 2
DirectSoundWaveData_0857A4A0::
	.incbin "sound/direct_sound_samples/0857A4A0.bin"

	.align 2
DirectSoundWaveData_08586578::
	.incbin "sound/direct_sound_samples/08586578.bin"

	.align 2
DirectSoundWaveData_0858F4BC::
	.incbin "sound/direct_sound_samples/0858F4BC.bin"

	.align 2
DirectSoundWaveData_08599C90::
	.incbin "sound/direct_sound_samples/08599C90.bin"

	.align 2
DirectSoundWaveData_085A6458::
	.incbin "sound/direct_sound_samples/085A6458.bin"

	.align 2
DirectSoundWaveData_085AECE4::
	.incbin "sound/direct_sound_samples/085AECE4.bin"

	.align 2
DirectSoundWaveData_085B5E68::
	.incbin "sound/direct_sound_samples/085B5E68.bin"

	.align 2
DirectSoundWaveData_085B91C8::
	.incbin "sound/direct_sound_samples/085B91C8.bin"

	.align 2
DirectSoundWaveData_085BC17C::
	.incbin "sound/direct_sound_samples/085BC17C.bin"

	.align 2
DirectSoundWaveData_085BE338::
	.incbin "sound/direct_sound_samples/085BE338.bin"

	.align 2
DirectSoundWaveData_085C6058::
	.incbin "sound/direct_sound_samples/085C6058.bin"

	.align 2
DirectSoundWaveData_085CA9D4::
	.incbin "sound/direct_sound_samples/085CA9D4.bin"

	.align 2
DirectSoundWaveData_085CE308::
	.incbin "sound/direct_sound_samples/085CE308.bin"

	.align 2
DirectSoundWaveData_085D0E4C::
	.incbin "sound/direct_sound_samples/085D0E4C.bin"

	.align 2
DirectSoundWaveData_085D7D48::
	.incbin "sound/direct_sound_samples/085D7D48.bin"

	.align 2
DirectSoundWaveData_085E0138::
	.incbin "sound/direct_sound_samples/085E0138.bin"

	.align 2
DirectSoundWaveData_085E40F0::
	.incbin "sound/direct_sound_samples/085E40F0.bin"

	.align 2
DirectSoundWaveData_085E6F74::
	.incbin "sound/direct_sound_samples/085E6F74.bin"

	.align 2
DirectSoundWaveData_085EAA28::
	.incbin "sound/direct_sound_samples/085EAA28.bin"

	.align 2
DirectSoundWaveData_085EDE58::
	.incbin "sound/direct_sound_samples/085EDE58.bin"

	.align 2
DirectSoundWaveData_085F05DC::
	.incbin "sound/direct_sound_samples/085F05DC.bin"

	.align 2
DirectSoundWaveData_085F8EAC::
	.incbin "sound/direct_sound_samples/085F8EAC.bin"

	.align 2
DirectSoundWaveData_085FD338::
	.incbin "sound/direct_sound_samples/085FD338.bin"

	.align 2
DirectSoundWaveData_086010A8::
	.incbin "sound/direct_sound_samples/086010A8.bin"

	.align 2
DirectSoundWaveData_08603AEC::
	.incbin "sound/direct_sound_samples/08603AEC.bin"

	.align 2
DirectSoundWaveData_08607294::
	.incbin "sound/direct_sound_samples/08607294.bin"

	.align 2
DirectSoundWaveData_0860B014::
	.incbin "sound/direct_sound_samples/0860B014.bin"

	.align 2
DirectSoundWaveData_0860CA10::
	.incbin "sound/direct_sound_samples/0860CA10.bin"

	.align 2
DirectSoundWaveData_08615C70::
	.incbin "sound/direct_sound_samples/08615C70.bin"

	.align 2
DirectSoundWaveData_0861D588::
	.incbin "sound/direct_sound_samples/0861D588.bin"

	.align 2
DirectSoundWaveData_08620EEC::
	.incbin "sound/direct_sound_samples/08620EEC.bin"

	.align 2
DirectSoundWaveData_08625D98::
	.incbin "sound/direct_sound_samples/08625D98.bin"

	.align 2
DirectSoundWaveData_0862E578::
	.incbin "sound/direct_sound_samples/0862E578.bin"

	.align 2
DirectSoundWaveData_0863CB0C::
	.incbin "sound/direct_sound_samples/0863CB0C.bin"

	.align 2
DirectSoundWaveData_086402D8::
	.incbin "sound/direct_sound_samples/086402D8.bin"

	.align 2
DirectSoundWaveData_08643528::
	.incbin "sound/direct_sound_samples/08643528.bin"

	.align 2
DirectSoundWaveData_08646F4C::
	.incbin "sound/direct_sound_samples/08646F4C.bin"

	.align 2
DirectSoundWaveData_0864A1C4::
	.incbin "sound/direct_sound_samples/0864A1C4.bin"

	.align 2
DirectSoundWaveData_0864E634::
	.incbin "sound/direct_sound_samples/0864E634.bin"

	.align 2
DirectSoundWaveData_086523DC::
	.incbin "sound/direct_sound_samples/086523DC.bin"

	.align 2
DirectSoundWaveData_08657508::
	.incbin "sound/direct_sound_samples/08657508.bin"

	.align 2
DirectSoundWaveData_0865A3D4::
	.incbin "sound/direct_sound_samples/0865A3D4.bin"

	.align 2
DirectSoundWaveData_0865EF54::
	.incbin "sound/direct_sound_samples/0865EF54.bin"

	.align 2
DirectSoundWaveData_086620C4::
	.incbin "sound/direct_sound_samples/086620C4.bin"

	.align 2
DirectSoundWaveData_08664894::
	.incbin "sound/direct_sound_samples/08664894.bin"

	.align 2
DirectSoundWaveData_08666664::
	.incbin "sound/direct_sound_samples/08666664.bin"

	.align 2
DirectSoundWaveData_08667C98::
	.incbin "sound/direct_sound_samples/08667C98.bin"

	.align 2
DirectSoundWaveData_086697EC::
	.incbin "sound/direct_sound_samples/086697EC.bin"

	.align 2
DirectSoundWaveData_0866AC7C::
	.incbin "sound/direct_sound_samples/0866AC7C.bin"

	.align 2
DirectSoundWaveData_0866C150::
	.incbin "sound/direct_sound_samples/0866C150.bin"

	.align 2
DirectSoundWaveData_0866D2DC::
	.incbin "sound/direct_sound_samples/0866D2DC.bin"

	.align 2
DirectSoundWaveData_0866E150::
	.incbin "sound/direct_sound_samples/0866E150.bin"

	.align 2
DirectSoundWaveData_0867163C::
	.incbin "sound/direct_sound_samples/0867163C.bin"

	.align 2
DirectSoundWaveData_08672AEC::
	.incbin "sound/direct_sound_samples/08672AEC.bin"

	.align 2
DirectSoundWaveData_086735E0::
	.incbin "sound/direct_sound_samples/086735E0.bin"

	.align 2
DirectSoundWaveData_086745D8::
	.incbin "sound/direct_sound_samples/086745D8.bin"

	.align 2
DirectSoundWaveData_08675088::
	.incbin "sound/direct_sound_samples/08675088.bin"

	.align 2
DirectSoundWaveData_0867AB50::
	.incbin "sound/direct_sound_samples/0867AB50.bin"

	.align 2
DirectSoundWaveData_0867CB1C::
	.incbin "sound/direct_sound_samples/0867CB1C.bin"

	.align 2
DirectSoundWaveData_0867ED8C::
	.incbin "sound/direct_sound_samples/0867ED8C.bin"

	.align 2
DirectSoundWaveData_08684C50::
	.incbin "sound/direct_sound_samples/08684C50.bin"

	.align 2
DirectSoundWaveData_0868A098::
	.incbin "sound/direct_sound_samples/0868A098.bin"

	.align 2
DirectSoundWaveData_086923E8::
	.incbin "sound/direct_sound_samples/086923E8.bin"

	.align 2
DirectSoundWaveData_0869A7EC::
	.incbin "sound/direct_sound_samples/0869A7EC.bin"

	.align 2
DirectSoundWaveData_086A4500::
	.incbin "sound/direct_sound_samples/086A4500.bin"

	.align 2
DirectSoundWaveData_086AB930::
	.incbin "sound/direct_sound_samples/086AB930.bin"

	.align 2
DirectSoundWaveData_086B2D50::
	.incbin "sound/direct_sound_samples/086B2D50.bin"

	.align 2
DirectSoundWaveData_086B58A4::
	.incbin "sound/direct_sound_samples/086B58A4.bin"

	.align 2
DirectSoundWaveData_086B89E4::
	.incbin "sound/direct_sound_samples/086B89E4.bin"

	.align 2
DirectSoundWaveData_086BBE18::
	.incbin "sound/direct_sound_samples/086BBE18.bin"

	.align 2
DirectSoundWaveData_086BD790::
	.incbin "sound/direct_sound_samples/086BD790.bin"

	.align 2
DirectSoundWaveData_086C207C::
	.incbin "sound/direct_sound_samples/086C207C.bin"

	.align 2
DirectSoundWaveData_086C6B0C::
	.incbin "sound/direct_sound_samples/086C6B0C.bin"

	.align 2
DirectSoundWaveData_086CB100::
	.incbin "sound/direct_sound_samples/086CB100.bin"

	.align 2
DirectSoundWaveData_086CE3D0::
	.incbin "sound/direct_sound_samples/086CE3D0.bin"

	.align 2
DirectSoundWaveData_086D15B4::
	.incbin "sound/direct_sound_samples/086D15B4.bin"

	.align 2
DirectSoundWaveData_086D50A4::
	.incbin "sound/direct_sound_samples/086D50A4.bin"

	.align 2
DirectSoundWaveData_086D88EC::
	.incbin "sound/direct_sound_samples/086D88EC.bin"

	.align 2
DirectSoundWaveData_086DC100::
	.incbin "sound/direct_sound_samples/086DC100.bin"

	.align 2
DirectSoundWaveData_086E25F8::
	.incbin "sound/direct_sound_samples/086E25F8.bin"

	.align 2
DirectSoundWaveData_086E6C00::
	.incbin "sound/direct_sound_samples/086E6C00.bin"

	.align 2
DirectSoundWaveData_086F1A2C::
	.incbin "sound/direct_sound_samples/086F1A2C.bin"

	.align 2
DirectSoundWaveData_086FE0CC::
	.incbin "sound/direct_sound_samples/086FE0CC.bin"

	.align 2
DirectSoundWaveData_08706784::
	.incbin "sound/direct_sound_samples/08706784.bin"

	.align 2
DirectSoundWaveData_0870F87C::
	.incbin "sound/direct_sound_samples/0870F87C.bin"

	.align 2
DirectSoundWaveData_08712430::
	.incbin "sound/direct_sound_samples/08712430.bin"

	.align 2
DirectSoundWaveData_08712B18::
	.incbin "sound/direct_sound_samples/08712B18.bin"

	.align 2
DirectSoundWaveData_0871465C::
	.incbin "sound/direct_sound_samples/0871465C.bin"

	.align 2
DirectSoundWaveData_08716774::
	.incbin "sound/direct_sound_samples/08716774.bin"

	.align 2
DirectSoundWaveData_08717FE4::
	.incbin "sound/direct_sound_samples/08717FE4.bin"

	.align 2
DirectSoundWaveData_0871F814::
	.incbin "sound/direct_sound_samples/0871F814.bin"

	.align 2
DirectSoundWaveData_08723BE8::
	.incbin "sound/direct_sound_samples/08723BE8.bin"

	.align 2
DirectSoundWaveData_0872D914::
	.incbin "sound/direct_sound_samples/0872D914.bin"

	.align 2
DirectSoundWaveData_08732460::
	.incbin "sound/direct_sound_samples/08732460.bin"

	.align 2
DirectSoundWaveData_08735D8C::
	.incbin "sound/direct_sound_samples/08735D8C.bin"

	.align 2
DirectSoundWaveData_0873A6F8::
	.incbin "sound/direct_sound_samples/0873A6F8.bin"

	.align 2
DirectSoundWaveData_0873D49C::
	.incbin "sound/direct_sound_samples/0873D49C.bin"

	.align 2
DirectSoundWaveData_087407A0::
	.incbin "sound/direct_sound_samples/087407A0.bin"

	.align 2
DirectSoundWaveData_08742964::
	.incbin "sound/direct_sound_samples/08742964.bin"

	.align 2
DirectSoundWaveData_087439B8::
	.incbin "sound/direct_sound_samples/087439B8.bin"

	.align 2
DirectSoundWaveData_08744F14::
	.incbin "sound/direct_sound_samples/08744F14.bin"

	.align 2
DirectSoundWaveData_08746BE4::
	.incbin "sound/direct_sound_samples/08746BE4.bin"

	.align 2
DirectSoundWaveData_087473B0::
	.incbin "sound/direct_sound_samples/087473B0.bin"

	.align 2
DirectSoundWaveData_0874A8D8::
	.incbin "sound/direct_sound_samples/0874A8D8.bin"

	.align 2
DirectSoundWaveData_0874E6C4::
	.incbin "sound/direct_sound_samples/0874E6C4.bin"

	.align 2
DirectSoundWaveData_08752298::
	.incbin "sound/direct_sound_samples/08752298.bin"

	.align 2
DirectSoundWaveData_087554AC::
	.incbin "sound/direct_sound_samples/087554AC.bin"

	.align 2
DirectSoundWaveData_08758FE0::
	.incbin "sound/direct_sound_samples/08758FE0.bin"

	.align 2
DirectSoundWaveData_0875D434::
	.incbin "sound/direct_sound_samples/0875D434.bin"

	.align 2
DirectSoundWaveData_08761C68::
	.incbin "sound/direct_sound_samples/08761C68.bin"

	.align 2
DirectSoundWaveData_08762674::
	.incbin "sound/direct_sound_samples/08762674.bin"

	.align 2
DirectSoundWaveData_08764DF8::
	.incbin "sound/direct_sound_samples/08764DF8.bin"

	.align 2
DirectSoundWaveData_0876AAD0::
	.incbin "sound/direct_sound_samples/0876AAD0.bin"

	.align 2
DirectSoundWaveData_0876DE84::
	.incbin "sound/direct_sound_samples/0876DE84.bin"

	.align 2
DirectSoundWaveData_08770668::
	.incbin "sound/direct_sound_samples/08770668.bin"

	.align 2
DirectSoundWaveData_08771820::
	.incbin "sound/direct_sound_samples/08771820.bin"

	.align 2
DirectSoundWaveData_08772D4C::
	.incbin "sound/direct_sound_samples/08772D4C.bin"

	.align 2
DirectSoundWaveData_087785E4::
	.incbin "sound/direct_sound_samples/087785E4.bin"

	.align 2
DirectSoundWaveData_08778C20::
	.incbin "sound/direct_sound_samples/08778C20.bin"

	.align 2
DirectSoundWaveData_087790A4::
	.incbin "sound/direct_sound_samples/087790A4.bin"

	.align 2
DirectSoundWaveData_08785928::
	.incbin "sound/direct_sound_samples/08785928.bin"

	.align 2
DirectSoundWaveData_08786A30::
	.incbin "sound/direct_sound_samples/08786A30.bin"

	.align 2
DirectSoundWaveData_087877D4::
	.incbin "sound/direct_sound_samples/087877D4.bin"

	.align 2
DirectSoundWaveData_08789800::
	.incbin "sound/direct_sound_samples/08789800.bin"

	.align 2
DirectSoundWaveData_0878A44C::
	.incbin "sound/direct_sound_samples/0878A44C.bin"

	.align 2
DirectSoundWaveData_0878B424::
	.incbin "sound/direct_sound_samples/0878B424.bin"

	.align 2
DirectSoundWaveData_0878BD58::
	.incbin "sound/direct_sound_samples/0878BD58.bin"

	.align 2
DirectSoundWaveData_0878E0EC::
	.incbin "sound/direct_sound_samples/0878E0EC.bin"

	.align 2
DirectSoundWaveData_0879213C::
	.incbin "sound/direct_sound_samples/0879213C.bin"

	.align 2
DirectSoundWaveData_08795550::
	.incbin "sound/direct_sound_samples/08795550.bin"

	.align 2
DirectSoundWaveData_087960CC::
	.incbin "sound/direct_sound_samples/087960CC.bin"

	.align 2
DirectSoundWaveData_08796C6C::
	.incbin "sound/direct_sound_samples/08796C6C.bin"

	.align 2
DirectSoundWaveData_0879758C::
	.incbin "sound/direct_sound_samples/0879758C.bin"

	.align 2
DirectSoundWaveData_08797E80::
	.incbin "sound/direct_sound_samples/08797E80.bin"

	.align 2
DirectSoundWaveData_0879877C::
	.incbin "sound/direct_sound_samples/0879877C.bin"

	.align 2
DirectSoundWaveData_08799AD4::
	.incbin "sound/direct_sound_samples/08799AD4.bin"

	.align 2
DirectSoundWaveData_0879B018::
	.incbin "sound/direct_sound_samples/0879B018.bin"

	.align 2
DirectSoundWaveData_087A1EEC::
	.incbin "sound/direct_sound_samples/087A1EEC.bin"

	.align 2
DirectSoundWaveData_087A25B4::
	.incbin "sound/direct_sound_samples/087A25B4.bin"

	.align 2
DirectSoundWaveData_087A3C64::
	.incbin "sound/direct_sound_samples/087A3C64.bin"

	.align 2
DirectSoundWaveData_087A48CC::
	.incbin "sound/direct_sound_samples/087A48CC.bin"

	.align 2
DirectSoundWaveData_087A5A30::
	.incbin "sound/direct_sound_samples/087A5A30.bin"

	.align 2
DirectSoundWaveData_087A712C::
	.incbin "sound/direct_sound_samples/087A712C.bin"

	.align 2
DirectSoundWaveData_087A8870::
	.incbin "sound/direct_sound_samples/087A8870.bin"

	.align 2
DirectSoundWaveData_087ACE44::
	.incbin "sound/direct_sound_samples/087ACE44.bin"

	.align 2
DirectSoundWaveData_087E21D8::
	.incbin "sound/direct_sound_samples/087E21D8.bin"

	.align 2
DirectSoundWaveData_087E316C::
	.incbin "sound/direct_sound_samples/087E316C.bin"

	.align 2
DirectSoundWaveData_087E591C::
	.incbin "sound/direct_sound_samples/087E591C.bin"

	.align 2
DirectSoundWaveData_087E9B28::
	.incbin "sound/direct_sound_samples/087E9B28.bin"

	.align 2
DirectSoundWaveData_087F1194::
	.incbin "sound/direct_sound_samples/087F1194.bin"

	.align 2
DirectSoundWaveData_087F1A2C::
	.incbin "sound/direct_sound_samples/087F1A2C.bin"

	.align 2
DirectSoundWaveData_087F7690::
	.incbin "sound/direct_sound_samples/087F7690.bin"

	.align 2
DirectSoundWaveData_087F7E64::
	.incbin "sound/direct_sound_samples/087F7E64.bin"

	.align 2
DirectSoundWaveData_087F8D94::
	.incbin "sound/direct_sound_samples/087F8D94.bin"

	.align 2
DirectSoundWaveData_087F9CBC::
	.incbin "sound/direct_sound_samples/087F9CBC.bin"

	.align 2
DirectSoundWaveData_087FB034::
	.incbin "sound/direct_sound_samples/087FB034.bin"

	.align 2
DirectSoundWaveData_087FCFF8::
	.incbin "sound/direct_sound_samples/087FCFF8.bin"

	.align 2
DirectSoundWaveData_087FFB5C::
	.incbin "sound/direct_sound_samples/087FFB5C.bin"

	.align 2
DirectSoundWaveData_08801E70::
	.incbin "sound/direct_sound_samples/08801E70.bin"

	.align 2
DirectSoundWaveData_08807784::
	.incbin "sound/direct_sound_samples/08807784.bin"

	.align 2
DirectSoundWaveData_0880A458::
	.incbin "sound/direct_sound_samples/0880A458.bin"

	.align 2
DirectSoundWaveData_0880CC14::
	.incbin "sound/direct_sound_samples/0880CC14.bin"

	.align 2
DirectSoundWaveData_0880D9D0::
	.incbin "sound/direct_sound_samples/0880D9D0.bin"

	.align 2
DirectSoundWaveData_0880FD64::
	.incbin "sound/direct_sound_samples/0880FD64.bin"

	.align 2
DirectSoundWaveData_08812898::
	.incbin "sound/direct_sound_samples/08812898.bin"

	.align 2
DirectSoundWaveData_08813600::
	.incbin "sound/direct_sound_samples/08813600.bin"

	.align 2
DirectSoundWaveData_088159B8::
	.incbin "sound/direct_sound_samples/088159B8.bin"

	.align 2
DirectSoundWaveData_0881B98C::
	.incbin "sound/direct_sound_samples/0881B98C.bin"

	.align 2
DirectSoundWaveData_0881C6B0::
	.incbin "sound/direct_sound_samples/0881C6B0.bin"

	.align 2
DirectSoundWaveData_0881D250::
	.incbin "sound/direct_sound_samples/0881D250.bin"

	.align 2
DirectSoundWaveData_08820B50::
	.incbin "sound/direct_sound_samples/08820B50.bin"

	.align 2
DirectSoundWaveData_088292E4::
	.incbin "sound/direct_sound_samples/088292E4.bin"

	.align 2
DirectSoundWaveData_0882BE78::
	.incbin "sound/direct_sound_samples/0882BE78.bin"

	.align 2
DirectSoundWaveData_0882D0E0::
	.incbin "sound/direct_sound_samples/0882D0E0.bin"

	.align 2
DirectSoundWaveData_0882E070::
	.incbin "sound/direct_sound_samples/0882E070.bin"

	.align 2
DirectSoundWaveData_0882F7C4::
	.incbin "sound/direct_sound_samples/0882F7C4.bin"

	.align 2
DirectSoundWaveData_088301E4::
	.incbin "sound/direct_sound_samples/088301E4.bin"

	.align 2
DirectSoundWaveData_08833578::
	.incbin "sound/direct_sound_samples/08833578.bin"

	.align 2
DirectSoundWaveData_08836B2C::
	.incbin "sound/direct_sound_samples/08836B2C.bin"

	.align 2
DirectSoundWaveData_0883D440::
	.incbin "sound/direct_sound_samples/0883D440.bin"

	.align 2
DirectSoundWaveData_0883E18C::
	.incbin "sound/direct_sound_samples/0883E18C.bin"

	.align 2
DirectSoundWaveData_08844AA0::
	.incbin "sound/direct_sound_samples/08844AA0.bin"

	.align 2
DirectSoundWaveData_0884F144::
	.incbin "sound/direct_sound_samples/0884F144.bin"

	.align 2
DirectSoundWaveData_08851698::
	.incbin "sound/direct_sound_samples/08851698.bin"

	.align 2
DirectSoundWaveData_0885273C::
	.incbin "sound/direct_sound_samples/0885273C.bin"

	.align 2
DirectSoundWaveData_088552C0::
	.incbin "sound/direct_sound_samples/088552C0.bin"

	.align 2
DirectSoundWaveData_0885A510::
	.incbin "sound/direct_sound_samples/0885A510.bin"

	.align 2
DirectSoundWaveData_0885E258::
	.incbin "sound/direct_sound_samples/0885E258.bin"

	.align 2
DirectSoundWaveData_08861C48::
	.incbin "sound/direct_sound_samples/08861C48.bin"

	.align 2
DirectSoundWaveData_088625A0::
	.incbin "sound/direct_sound_samples/088625A0.bin"

	.align 2
DirectSoundWaveData_08863FC4::
	.incbin "sound/direct_sound_samples/08863FC4.bin"

	.align 2
DirectSoundWaveData_08864588::
	.incbin "sound/direct_sound_samples/08864588.bin"

	.align 2
DirectSoundWaveData_0886C1A8::
	.incbin "sound/direct_sound_samples/0886C1A8.bin"

	.align 2
DirectSoundWaveData_08872E10::
	.incbin "sound/direct_sound_samples/08872E10.bin"

	.align 2
DirectSoundWaveData_08875410::
	.incbin "sound/direct_sound_samples/08875410.bin"

	.align 2
DirectSoundWaveData_08878124::
	.incbin "sound/direct_sound_samples/08878124.bin"

	.align 2
DirectSoundWaveData_08879E10::
	.incbin "sound/direct_sound_samples/08879E10.bin"

	.align 2
DirectSoundWaveData_08882824::
	.incbin "sound/direct_sound_samples/08882824.bin"

	.align 2
DirectSoundWaveData_088889FC::
	.incbin "sound/direct_sound_samples/088889FC.bin"

	.align 2
DirectSoundWaveData_0888BB40::
	.incbin "sound/direct_sound_samples/0888BB40.bin"

	.align 2
DirectSoundWaveData_0888E114::
	.incbin "sound/direct_sound_samples/0888E114.bin"

	.align 2
DirectSoundWaveData_08890E64::
	.incbin "sound/direct_sound_samples/08890E64.bin"

	.align 2
DirectSoundWaveData_0889CA0C::
	.incbin "sound/direct_sound_samples/0889CA0C.bin"

	.align 2
DirectSoundWaveData_0889FC4C::
	.incbin "sound/direct_sound_samples/0889FC4C.bin"

	.align 2
DirectSoundWaveData_088A41C4::
	.incbin "sound/direct_sound_samples/088A41C4.bin"

	.align 2
DirectSoundWaveData_088A61A0::
	.incbin "sound/direct_sound_samples/088A61A0.bin"

	.align 2
DirectSoundWaveData_088A69A4::
	.incbin "sound/direct_sound_samples/088A69A4.bin"

	.align 2
DirectSoundWaveData_088AC738::
	.incbin "sound/direct_sound_samples/088AC738.bin"

	.align 2
DirectSoundWaveData_088ACF74::
	.incbin "sound/direct_sound_samples/088ACF74.bin"

	.align 2
DirectSoundWaveData_088ADD54::
	.incbin "sound/direct_sound_samples/088ADD54.bin"

	.align 2
DirectSoundWaveData_088B4AE4::
	.incbin "sound/direct_sound_samples/088B4AE4.bin"

	.align 2
DirectSoundWaveData_088BA7B4::
	.incbin "sound/direct_sound_samples/088BA7B4.bin"

	.align 2
DirectSoundWaveData_088C1F5C::
	.incbin "sound/direct_sound_samples/088C1F5C.bin"

	.align 2
DirectSoundWaveData_088C4F78::
	.incbin "sound/direct_sound_samples/088C4F78.bin"

	.align 2
DirectSoundWaveData_088D00DC::
	.incbin "sound/direct_sound_samples/088D00DC.bin"

	.align 2
DirectSoundWaveData_088D0780::
	.incbin "sound/direct_sound_samples/088D0780.bin"

	.align 2
DirectSoundWaveData_088D6168::
	.incbin "sound/direct_sound_samples/088D6168.bin"

	.align 2
DirectSoundWaveData_088EAE50::
	.incbin "sound/direct_sound_samples/088EAE50.bin"

	.align 2
DirectSoundWaveData_088EEB84::
	.incbin "sound/direct_sound_samples/088EEB84.bin"

	.align 2
DirectSoundWaveData_088EF548::
	.incbin "sound/direct_sound_samples/088EF548.bin"

	.align 2
DirectSoundWaveData_088EFB1C::
	.incbin "sound/direct_sound_samples/088EFB1C.bin"

	.align 2
DirectSoundWaveData_088F26F0::
	.incbin "sound/direct_sound_samples/088F26F0.bin"

	.align 2
DirectSoundWaveData_088F3080::
	.incbin "sound/direct_sound_samples/088F3080.bin"

	.align 2
DirectSoundWaveData_088F6EC4::
	.incbin "sound/direct_sound_samples/088F6EC4.bin"

	.align 2
DirectSoundWaveData_088F77B4::
	.incbin "sound/direct_sound_samples/088F77B4.bin"

	.align 2
DirectSoundWaveData_088F8C64::
	.incbin "sound/direct_sound_samples/088F8C64.bin"

	.align 2
DirectSoundWaveData_088F95FC::
	.incbin "sound/direct_sound_samples/088F95FC.bin"

	.align 2
DirectSoundWaveData_089006C0::
	.incbin "sound/direct_sound_samples/089006C0.bin"

	.align 2
DirectSoundWaveData_08905438::
	.incbin "sound/direct_sound_samples/08905438.bin"

	.align 2
DirectSoundWaveData_08906A1C::
	.incbin "sound/direct_sound_samples/08906A1C.bin"

	.align 2
DirectSoundWaveData_08907508::
	.incbin "sound/direct_sound_samples/08907508.bin"

	.align 2
DirectSoundWaveData_08907E38::
	.incbin "sound/direct_sound_samples/08907E38.bin"

	.align 2
DirectSoundWaveData_0890DF7C::
	.incbin "sound/direct_sound_samples/0890DF7C.bin"

	.align 2
DirectSoundWaveData_0890EAC0::
	.incbin "sound/direct_sound_samples/0890EAC0.bin"

	.align 2
DirectSoundWaveData_0890F788::
	.incbin "sound/direct_sound_samples/0890F788.bin"

	.align 2
DirectSoundWaveData_08911240::
	.incbin "sound/direct_sound_samples/08911240.bin"

	.align 2
DirectSoundWaveData_089147E0::
	.incbin "sound/direct_sound_samples/089147E0.bin"

	.align 2
DirectSoundWaveData_08916764::
	.incbin "sound/direct_sound_samples/08916764.bin"

	.align 2
DirectSoundWaveData_08918AE8::
	.incbin "sound/direct_sound_samples/08918AE8.bin"

	.align 2
DirectSoundWaveData_089199E0::
	.incbin "sound/direct_sound_samples/089199E0.bin"

	.align 2
DirectSoundWaveData_0891C6C4::
	.incbin "sound/direct_sound_samples/0891C6C4.bin"

	.align 2
DirectSoundWaveData_0891ED18::
	.incbin "sound/direct_sound_samples/0891ED18.bin"

	.align 2
DirectSoundWaveData_08920434::
	.incbin "sound/direct_sound_samples/08920434.bin"

	.align 2
DirectSoundWaveData_089233F4::
	.incbin "sound/direct_sound_samples/089233F4.bin"

	.align 2
DirectSoundWaveData_08927A08::
	.incbin "sound/direct_sound_samples/08927A08.bin"

	.align 2
DirectSoundWaveData_0892E3CC::
	.incbin "sound/direct_sound_samples/0892E3CC.bin"

	.align 2
DirectSoundWaveData_089327C4::
	.incbin "sound/direct_sound_samples/089327C4.bin"

	.align 2
DirectSoundWaveData_08933C1C::
	.incbin "sound/direct_sound_samples/08933C1C.bin"

	.align 2
DirectSoundWaveData_089351AC::
	.incbin "sound/direct_sound_samples/089351AC.bin"

	.align 2
DirectSoundWaveData_089378C8::
	.incbin "sound/direct_sound_samples/089378C8.bin"

	.align 2
DirectSoundWaveData_0893D428::
	.incbin "sound/direct_sound_samples/0893D428.bin"

	.align 2
DirectSoundWaveData_08943AA0::
	.incbin "sound/direct_sound_samples/08943AA0.bin"

	.align 2
DirectSoundWaveData_089456C8::
	.incbin "sound/direct_sound_samples/089456C8.bin"

	.align 2
DirectSoundWaveData_089464F4::
	.incbin "sound/direct_sound_samples/089464F4.bin"

	.align 2
DirectSoundWaveData_08948820::
	.incbin "sound/direct_sound_samples/08948820.bin"

	.align 2
DirectSoundWaveData_0894A9B8::
	.incbin "sound/direct_sound_samples/0894A9B8.bin"

	.align 2
DirectSoundWaveData_0894B0DC::
	.incbin "sound/direct_sound_samples/0894B0DC.bin"

	.align 2
DirectSoundWaveData_0894DA24::
	.incbin "sound/direct_sound_samples/0894DA24.bin"

	.align 2
DirectSoundWaveData_08950318::
	.incbin "sound/direct_sound_samples/08950318.bin"

	.align 2
DirectSoundWaveData_08952AC0::
	.incbin "sound/direct_sound_samples/08952AC0.bin"

	.align 2
DirectSoundWaveData_08957670::
	.incbin "sound/direct_sound_samples/08957670.bin"

	.align 2
DirectSoundWaveData_08958ED0::
	.incbin "sound/direct_sound_samples/08958ED0.bin"

	.align 2
DirectSoundWaveData_0895A8E4::
	.incbin "sound/direct_sound_samples/0895A8E4.bin"

	.align 2
DirectSoundWaveData_08962E78::
	.incbin "sound/direct_sound_samples/08962E78.bin"

	.align 2
DirectSoundWaveData_08964D8C::
	.incbin "sound/direct_sound_samples/08964D8C.bin"

	.align 2
DirectSoundWaveData_08969758::
	.incbin "sound/direct_sound_samples/08969758.bin"

	.align 2
DirectSoundWaveData_0896A160::
	.incbin "sound/direct_sound_samples/0896A160.bin"

	.align 2
DirectSoundWaveData_08971DAC::
	.incbin "sound/direct_sound_samples/08971DAC.bin"

	.align 2
DirectSoundWaveData_08973D04::
	.incbin "sound/direct_sound_samples/08973D04.bin"

	.align 2
DirectSoundWaveData_08975A7C::
	.incbin "sound/direct_sound_samples/08975A7C.bin"

	.align 2
DirectSoundWaveData_0897BBCC::
	.incbin "sound/direct_sound_samples/0897BBCC.bin"

	.align 2
DirectSoundWaveData_0897C3CC::
	.incbin "sound/direct_sound_samples/0897C3CC.bin"

	.align 2
DirectSoundWaveData_08980A50::
	.incbin "sound/direct_sound_samples/08980A50.bin"

	.align 2
DirectSoundWaveData_08988324::
	.incbin "sound/direct_sound_samples/08988324.bin"

	.align 2
DirectSoundWaveData_0898CF5C::
	.incbin "sound/direct_sound_samples/0898CF5C.bin"

	.align 2
DirectSoundWaveData_08992DA0::
	.incbin "sound/direct_sound_samples/08992DA0.bin"

	.align 2
DirectSoundWaveData_089936F8::
	.incbin "sound/direct_sound_samples/089936F8.bin"

	.align 2
DirectSoundWaveData_08993D70::
	.incbin "sound/direct_sound_samples/08993D70.bin"

	.align 2
DirectSoundWaveData_089964D4::
	.incbin "sound/direct_sound_samples/089964D4.bin"

	.align 2
DirectSoundWaveData_0899705C::
	.incbin "sound/direct_sound_samples/0899705C.bin"

	.align 2
DirectSoundWaveData_0899849C::
	.incbin "sound/direct_sound_samples/0899849C.bin"

	.align 2
DirectSoundWaveData_0899AB04::
	.incbin "sound/direct_sound_samples/0899AB04.bin"

	.align 2
DirectSoundWaveData_0899B05C::
	.incbin "sound/direct_sound_samples/0899B05C.bin"

	.align 2
DirectSoundWaveData_0899C46C::
	.incbin "sound/direct_sound_samples/0899C46C.bin"

	.align 2
DirectSoundWaveData_089A1654::
	.incbin "sound/direct_sound_samples/089A1654.bin"

	.align 2
DirectSoundWaveData_089A3768::
	.incbin "sound/direct_sound_samples/089A3768.bin"

	.align 2
DirectSoundWaveData_089A6AE4::
	.incbin "sound/direct_sound_samples/089A6AE4.bin"

	.align 2
DirectSoundWaveData_089A7038::
	.incbin "sound/direct_sound_samples/089A7038.bin"

	.align 2
DirectSoundWaveData_089A8114::
	.incbin "sound/direct_sound_samples/089A8114.bin"

	.align 2
DirectSoundWaveData_089A94B8::
	.incbin "sound/direct_sound_samples/089A94B8.bin"

	.align 2
DirectSoundWaveData_089AAD68::
	.incbin "sound/direct_sound_samples/089AAD68.bin"

	.align 2
DirectSoundWaveData_089AC620::
	.incbin "sound/direct_sound_samples/089AC620.bin"

	.align 2
DirectSoundWaveData_089ADEE0::
	.incbin "sound/direct_sound_samples/089ADEE0.bin"

	.align 2
DirectSoundWaveData_089AF788::
	.incbin "sound/direct_sound_samples/089AF788.bin"

	.align 2
DirectSoundWaveData_089B103C::
	.incbin "sound/direct_sound_samples/089B103C.bin"

	.align 2
DirectSoundWaveData_089B2900::
	.incbin "sound/direct_sound_samples/089B2900.bin"

	.align 2
DirectSoundWaveData_089B41A4::
	.incbin "sound/direct_sound_samples/089B41A4.bin"

	.align 2
DirectSoundWaveData_089B5CF0::
	.incbin "sound/direct_sound_samples/089B5CF0.bin"

	.align 2
DirectSoundWaveData_089B660C::
	.incbin "sound/direct_sound_samples/089B660C.bin"

	.align 2
DirectSoundWaveData_089B710C::
	.incbin "sound/direct_sound_samples/089B710C.bin"

	.align 2
DirectSoundWaveData_089B89C0::
	.incbin "sound/direct_sound_samples/089B89C0.bin"

	.align 2
DirectSoundWaveData_089BA284::
	.incbin "sound/direct_sound_samples/089BA284.bin"

	.align 2
DirectSoundWaveData_089BBB3C::
	.incbin "sound/direct_sound_samples/089BBB3C.bin"

	.align 2
DirectSoundWaveData_089C3FA8::
	.incbin "sound/direct_sound_samples/089C3FA8.bin"

	.align 2
DirectSoundWaveData_089CBDCC::
	.incbin "sound/direct_sound_samples/089CBDCC.bin"

	.align 2
DirectSoundWaveData_089CDF88::
	.incbin "sound/direct_sound_samples/089CDF88.bin"

	.align 2
DirectSoundWaveData_089CF054::
	.incbin "sound/direct_sound_samples/089CF054.bin"

	.align 2
DirectSoundWaveData_089D3484::
	.incbin "sound/direct_sound_samples/089D3484.bin"

	.align 2
DirectSoundWaveData_089D4654::
	.incbin "sound/direct_sound_samples/089D4654.bin"

	.align 2
DirectSoundWaveData_089D6174::
	.incbin "sound/direct_sound_samples/089D6174.bin"

	.align 2
DirectSoundWaveData_089D7C38::
	.incbin "sound/direct_sound_samples/089D7C38.bin"

	.align 2
DirectSoundWaveData_089D9BF0::
	.incbin "sound/direct_sound_samples/089D9BF0.bin"

	.align 2
DirectSoundWaveData_089DB128::
	.incbin "sound/direct_sound_samples/089DB128.bin"

	.align 2
DirectSoundWaveData_089DC91C::
	.incbin "sound/direct_sound_samples/089DC91C.bin"

	.align 2
DirectSoundWaveData_089DD09C::
	.incbin "sound/direct_sound_samples/089DD09C.bin"

	.align 2
DirectSoundWaveData_089DDDA8::
	.incbin "sound/direct_sound_samples/089DDDA8.bin"

	.align 2
DirectSoundWaveData_089DFA3C::
	.incbin "sound/direct_sound_samples/089DFA3C.bin"

	.align 2
DirectSoundWaveData_089E0B4C::
	.incbin "sound/direct_sound_samples/089E0B4C.bin"

	.align 2
DirectSoundWaveData_089E210C::
	.incbin "sound/direct_sound_samples/089E210C.bin"

	.align 2
DirectSoundWaveData_089E37C0::
	.incbin "sound/direct_sound_samples/089E37C0.bin"

	.align 2
DirectSoundWaveData_089E4710::
	.incbin "sound/direct_sound_samples/089E4710.bin"

	.align 2
DirectSoundWaveData_089E52D8::
	.incbin "sound/direct_sound_samples/089E52D8.bin"

	.align 2
DirectSoundWaveData_089E5D44::
	.incbin "sound/direct_sound_samples/089E5D44.bin"

	.align 2
DirectSoundWaveData_089E6B90::
	.incbin "sound/direct_sound_samples/089E6B90.bin"

	.align 2
DirectSoundWaveData_089E7C5C::
	.incbin "sound/direct_sound_samples/089E7C5C.bin"

	.align 2
DirectSoundWaveData_089E8230::
	.incbin "sound/direct_sound_samples/089E8230.bin"

	.align 2
DirectSoundWaveData_089E9288::
	.incbin "sound/direct_sound_samples/089E9288.bin"

	.align 2
DirectSoundWaveData_089E9DD4::
	.incbin "sound/direct_sound_samples/089E9DD4.bin"

	.align 2
DirectSoundWaveData_089E9FE4::
	.incbin "sound/direct_sound_samples/089E9FE4.bin"

	.align 2
DirectSoundWaveData_089EB8CC::
	.incbin "sound/direct_sound_samples/089EB8CC.bin"

	.align 2
DirectSoundWaveData_089EBE2C::
	.incbin "sound/direct_sound_samples/089EBE2C.bin"

	.align 2
DirectSoundWaveData_089ECC20::
	.incbin "sound/direct_sound_samples/089ECC20.bin"

	.align 2
DirectSoundWaveData_089EDBDC::
	.incbin "sound/direct_sound_samples/089EDBDC.bin"

	.align 2
DirectSoundWaveData_089EE0D8::
	.incbin "sound/direct_sound_samples/089EE0D8.bin"

	.align 2
DirectSoundWaveData_089EE494::
	.incbin "sound/direct_sound_samples/089EE494.bin"

	.align 2
DirectSoundWaveData_089EE714::
	.incbin "sound/direct_sound_samples/089EE714.bin"

	.align 2
DirectSoundWaveData_089EF1A8::
	.incbin "sound/direct_sound_samples/089EF1A8.bin"

	.align 2
DirectSoundWaveData_089F10B0::
	.incbin "sound/direct_sound_samples/089F10B0.bin"

	.align 2
DirectSoundWaveData_089F2A78::
	.incbin "sound/direct_sound_samples/089F2A78.bin"

	.align 2
DirectSoundWaveData_089F3274::
	.incbin "sound/direct_sound_samples/089F3274.bin"

	.align 2
DirectSoundWaveData_089F3958::
	.incbin "sound/direct_sound_samples/089F3958.bin"

	.align 2
DirectSoundWaveData_089F4C94::
	.incbin "sound/direct_sound_samples/089F4C94.bin"

	.align 2
DirectSoundWaveData_089F65B8::
	.incbin "sound/direct_sound_samples/089F65B8.bin"

	.align 2
DirectSoundWaveData_089F766C::
	.incbin "sound/direct_sound_samples/089F766C.bin"

	.align 2
DirectSoundWaveData_089F89B0::
	.incbin "sound/direct_sound_samples/089F89B0.bin"

	.align 2
DirectSoundWaveData_089F903C::
	.incbin "sound/direct_sound_samples/089F903C.bin"

	.align 2
DirectSoundWaveData_089FAB80::
	.incbin "sound/direct_sound_samples/089FAB80.bin"

	.align 2
DirectSoundWaveData_089FB970::
	.incbin "sound/direct_sound_samples/089FB970.bin"

	.align 2
DirectSoundWaveData_089FCB34::
	.incbin "sound/direct_sound_samples/089FCB34.bin"

	.align 2
DirectSoundWaveData_089FEB38::
	.incbin "sound/direct_sound_samples/089FEB38.bin"

	.align 2
DirectSoundWaveData_089FFBC8::
	.incbin "sound/direct_sound_samples/089FFBC8.bin"

	.align 2
DirectSoundWaveData_08A01C80::
	.incbin "sound/direct_sound_samples/08A01C80.bin"

	.align 2
DirectSoundWaveData_08A01DC0::
	.incbin "sound/direct_sound_samples/08A01DC0.bin"

	.align 2
DirectSoundWaveData_08A03A04::
	.incbin "sound/direct_sound_samples/08A03A04.bin"

	.align 2
DirectSoundWaveData_08A06794::
	.incbin "sound/direct_sound_samples/08A06794.bin"

	.align 2
DirectSoundWaveData_08A0B7DC::
	.incbin "sound/direct_sound_samples/08A0B7DC.bin"

	.align 2
DirectSoundWaveData_08A11338::
	.incbin "sound/direct_sound_samples/08A11338.bin"

	.align 2
DirectSoundWaveData_08A11614::
	.incbin "sound/direct_sound_samples/08A11614.bin"

	.align 2
DirectSoundWaveData_08A17520::
	.incbin "sound/direct_sound_samples/08A17520.bin"

	.align 2
DirectSoundWaveData_08A1C514::
	.incbin "sound/direct_sound_samples/08A1C514.bin"

	.align 2
DirectSoundWaveData_08A1DD68::
	.incbin "sound/direct_sound_samples/08A1DD68.bin"

	.align 2
DirectSoundWaveData_08A21638::
	.incbin "sound/direct_sound_samples/08A21638.bin"

	.align 2
DirectSoundWaveData_08A241EC::
	.incbin "sound/direct_sound_samples/08A241EC.bin"

	.align 2
DirectSoundWaveData_08A26F48::
	.incbin "sound/direct_sound_samples/08A26F48.bin"

	.align 2
DirectSoundWaveData_08A2A260::
	.incbin "sound/direct_sound_samples/08A2A260.bin"

	.align 2
DirectSoundWaveData_08A2F27C::
	.incbin "sound/direct_sound_samples/08A2F27C.bin"

	.align 2
DirectSoundWaveData_08A3418C::
	.incbin "sound/direct_sound_samples/08A3418C.bin"

	.align 2
DirectSoundWaveData_08A35A10::
	.incbin "sound/direct_sound_samples/08A35A10.bin"

	.align 2
DirectSoundWaveData_08A38204::
	.incbin "sound/direct_sound_samples/08A38204.bin"

	.align 2
DirectSoundWaveData_08A3A558::
	.incbin "sound/direct_sound_samples/08A3A558.bin"

	.align 2
DirectSoundWaveData_08A3C9EC::
	.incbin "sound/direct_sound_samples/08A3C9EC.bin"

	.align 2
DirectSoundWaveData_08A4258C::
	.incbin "sound/direct_sound_samples/08A4258C.bin"

	.align 2
DirectSoundWaveData_08A46400::
	.incbin "sound/direct_sound_samples/08A46400.bin"

	.align 2
DirectSoundWaveData_08A47028::
	.incbin "sound/direct_sound_samples/08A47028.bin"

	.align 2
DirectSoundWaveData_08A486C4::
	.incbin "sound/direct_sound_samples/08A486C4.bin"

	.align 2
DirectSoundWaveData_08A49634::
	.incbin "sound/direct_sound_samples/08A49634.bin"

	.align 2
DirectSoundWaveData_08A4BCA8::
	.incbin "sound/direct_sound_samples/08A4BCA8.bin"

	.align 2
DirectSoundWaveData_08A4F0A0::
	.incbin "sound/direct_sound_samples/08A4F0A0.bin"

	.align 2
DirectSoundWaveData_08A55B04::
	.incbin "sound/direct_sound_samples/08A55B04.bin"

	.align 2
DirectSoundWaveData_08A56258::
	.incbin "sound/direct_sound_samples/08A56258.bin"

	.align 2
DirectSoundWaveData_08A57540::
	.incbin "sound/direct_sound_samples/08A57540.bin"

	.align 2
DirectSoundWaveData_08A5A480::
	.incbin "sound/direct_sound_samples/08A5A480.bin"

	.align 2
DirectSoundWaveData_08A60648::
	.incbin "sound/direct_sound_samples/08A60648.bin"

	.align 2
DirectSoundWaveData_08A68C94::
	.incbin "sound/direct_sound_samples/08A68C94.bin"

	.align 2
DirectSoundWaveData_08A6A424::
	.incbin "sound/direct_sound_samples/08A6A424.bin"

	.align 2
DirectSoundWaveData_08A6C978::
	.incbin "sound/direct_sound_samples/08A6C978.bin"

	.align 2
DirectSoundWaveData_08A6FD60::
	.incbin "sound/direct_sound_samples/08A6FD60.bin"

	.align 2
DirectSoundWaveData_08A7380C::
	.incbin "sound/direct_sound_samples/08A7380C.bin"

	.align 2
DirectSoundWaveData_08A79C8C::
	.incbin "sound/direct_sound_samples/08A79C8C.bin"

	.align 2
DirectSoundWaveData_08A7BAAC::
	.incbin "sound/direct_sound_samples/08A7BAAC.bin"

	.align 2
DirectSoundWaveData_08A8F564::
	.incbin "sound/direct_sound_samples/08A8F564.bin"

	.align 2
DirectSoundWaveData_08A92AB8::
	.incbin "sound/direct_sound_samples/08A92AB8.bin"

	.align 2
DirectSoundWaveData_08A968B8::
	.incbin "sound/direct_sound_samples/08A968B8.bin"

	.align 2
DirectSoundWaveData_08A9CA0C::
	.incbin "sound/direct_sound_samples/08A9CA0C.bin"

	.align 2
DirectSoundWaveData_08A9E15C::
	.incbin "sound/direct_sound_samples/08A9E15C.bin"

	.align 2
DirectSoundWaveData_08A9FA30::
	.incbin "sound/direct_sound_samples/08A9FA30.bin"

	.align 2
DirectSoundWaveData_08AA174C::
	.incbin "sound/direct_sound_samples/08AA174C.bin"

	.align 2
DirectSoundWaveData_08AA84E0::
	.incbin "sound/direct_sound_samples/08AA84E0.bin"

	.align 2
DirectSoundWaveData_08AA8988::
	.incbin "sound/direct_sound_samples/08AA8988.bin"

	.align 2
DirectSoundWaveData_08AAB188::
	.incbin "sound/direct_sound_samples/08AAB188.bin"

	.align 2
DirectSoundWaveData_08AACBC4::
	.incbin "sound/direct_sound_samples/08AACBC4.bin"

	.align 2
DirectSoundWaveData_08AAE948::
	.incbin "sound/direct_sound_samples/08AAE948.bin"

	.align 2
DirectSoundWaveData_08AB1684::
	.incbin "sound/direct_sound_samples/08AB1684.bin"

	.align 2
DirectSoundWaveData_08AB46F4::
	.incbin "sound/direct_sound_samples/08AB46F4.bin"

	.align 2
DirectSoundWaveData_08AB5A10::
	.incbin "sound/direct_sound_samples/08AB5A10.bin"

	.align 2
DirectSoundWaveData_08AB9518::
	.incbin "sound/direct_sound_samples/08AB9518.bin"

	.align 2
DirectSoundWaveData_08ABF058::
	.incbin "sound/direct_sound_samples/08ABF058.bin"

	.align 2
DirectSoundWaveData_08AC2760::
	.incbin "sound/direct_sound_samples/08AC2760.bin"

	.align 2
DirectSoundWaveData_08AC3EB4::
	.incbin "sound/direct_sound_samples/08AC3EB4.bin"

	.align 2
DirectSoundWaveData_08AC5178::
	.incbin "sound/direct_sound_samples/08AC5178.bin"

	.align 2
DirectSoundWaveData_08AC886C::
	.incbin "sound/direct_sound_samples/08AC886C.bin"

	.align 2
DirectSoundWaveData_08ACBB60::
	.incbin "sound/direct_sound_samples/08ACBB60.bin"

	.align 2
DirectSoundWaveData_08ACED2C::
	.incbin "sound/direct_sound_samples/08ACED2C.bin"

	.align 2
DirectSoundWaveData_08AD14C0::
	.incbin "sound/direct_sound_samples/08AD14C0.bin"

	.align 2
DirectSoundWaveData_08AD6470::
	.incbin "sound/direct_sound_samples/08AD6470.bin"

	.align 2
DirectSoundWaveData_08AE6D04::
	.incbin "sound/direct_sound_samples/08AE6D04.bin"

	.align 2
DirectSoundWaveData_08AEC310::
	.incbin "sound/direct_sound_samples/08AEC310.bin"

	.align 2
DirectSoundWaveData_08AF1764::
	.incbin "sound/direct_sound_samples/08AF1764.bin"

	.align 2
DirectSoundWaveData_08AF32A4::
	.incbin "sound/direct_sound_samples/08AF32A4.bin"

	.align 2
DirectSoundWaveData_08AF45A0::
	.incbin "sound/direct_sound_samples/08AF45A0.bin"

	.align 2
DirectSoundWaveData_08AF50FC::
	.incbin "sound/direct_sound_samples/08AF50FC.bin"

	.align 2
DirectSoundWaveData_08AF6068::
	.incbin "sound/direct_sound_samples/08AF6068.bin"

	.align 2
DirectSoundWaveData_08AF6D28::
	.incbin "sound/direct_sound_samples/08AF6D28.bin"

	.align 2
DirectSoundWaveData_08AF78A8::
	.incbin "sound/direct_sound_samples/08AF78A8.bin"

	.align 2
DirectSoundWaveData_08AF7B6C::
	.incbin "sound/direct_sound_samples/08AF7B6C.bin"

	.align 2
DirectSoundWaveData_08AF81D0::
	.incbin "sound/direct_sound_samples/08AF81D0.bin"

	.align 2
DirectSoundWaveData_08AF853C::
	.incbin "sound/direct_sound_samples/08AF853C.bin"

	.align 2
DirectSoundWaveData_08AF8A30::
	.incbin "sound/direct_sound_samples/08AF8A30.bin"

	.align 2
DirectSoundWaveData_08AF9118::
	.incbin "sound/direct_sound_samples/08AF9118.bin"

	.align 2
DirectSoundWaveData_08AF96FC::
	.incbin "sound/direct_sound_samples/08AF96FC.bin"

	.align 2
DirectSoundWaveData_08AF9E30::
	.incbin "sound/direct_sound_samples/08AF9E30.bin"

	.align 2
DirectSoundWaveData_08AFA6DC::
	.incbin "sound/direct_sound_samples/08AFA6DC.bin"

	.align 2
DirectSoundWaveData_08AFAC64::
	.incbin "sound/direct_sound_samples/08AFAC64.bin"

	.align 2
DirectSoundWaveData_08AFB58C::
	.incbin "sound/direct_sound_samples/08AFB58C.bin"

	.align 2
DirectSoundWaveData_08AFBC14::
	.incbin "sound/direct_sound_samples/08AFBC14.bin"

	.align 2
DirectSoundWaveData_08AFC250::
	.incbin "sound/direct_sound_samples/08AFC250.bin"

	.align 2
DirectSoundWaveData_08AFC724::
	.incbin "sound/direct_sound_samples/08AFC724.bin"

	.align 2
DirectSoundWaveData_08AFCBC4::
	.incbin "sound/direct_sound_samples/08AFCBC4.bin"

	.align 2
DirectSoundWaveData_08AFD12C::
	.incbin "sound/direct_sound_samples/08AFD12C.bin"

	.align 2
DirectSoundWaveData_08AFD8A0::
	.incbin "sound/direct_sound_samples/08AFD8A0.bin"

	.align 2
DirectSoundWaveData_08AFDDE4::
	.incbin "sound/direct_sound_samples/08AFDDE4.bin"

	.align 2
DirectSoundWaveData_08AFE3C4::
	.incbin "sound/direct_sound_samples/08AFE3C4.bin"

	.align 2
DirectSoundWaveData_08AFECBC::
	.incbin "sound/direct_sound_samples/08AFECBC.bin"

	.align 2
DirectSoundWaveData_08AFF428::
	.incbin "sound/direct_sound_samples/08AFF428.bin"

	.align 2
DirectSoundWaveData_08AFFCA0::
	.incbin "sound/direct_sound_samples/08AFFCA0.bin"

	.align 2
DirectSoundWaveData_08B00790::
	.incbin "sound/direct_sound_samples/08B00790.bin"

	.align 2
DirectSoundWaveData_08B010B0::
	.incbin "sound/direct_sound_samples/08B010B0.bin"

	.align 2
DirectSoundWaveData_08B01A4C::
	.incbin "sound/direct_sound_samples/08B01A4C.bin"

	.align 2
DirectSoundWaveData_08B026F8::
	.incbin "sound/direct_sound_samples/08B026F8.bin"

	.align 2
DirectSoundWaveData_08B03150::
	.incbin "sound/direct_sound_samples/08B03150.bin"

	.align 2
DirectSoundWaveData_08B0325C::
	.incbin "sound/direct_sound_samples/08B0325C.bin"

	.align 2
DirectSoundWaveData_08B0328C::
	.incbin "sound/direct_sound_samples/08B0328C.bin"

	.align 2
DirectSoundWaveData_08B032BC::
	.incbin "sound/direct_sound_samples/08B032BC.bin"

	.align 2
DirectSoundWaveData_08B032EC::
	.incbin "sound/direct_sound_samples/08B032EC.bin"

	.align 2
DirectSoundWaveData_08B0331C::
	.incbin "sound/direct_sound_samples/08B0331C.bin"

	.align 2
DirectSoundWaveData_08B0334C::
	.incbin "sound/direct_sound_samples/08B0334C.bin"

	.align 2
DirectSoundWaveData_08B0337C::
	.incbin "sound/direct_sound_samples/08B0337C.bin"

	.align 2
DirectSoundWaveData_08B04670::
	.incbin "sound/direct_sound_samples/08B04670.bin"

	.align 2
DirectSoundWaveData_08B05944::
	.incbin "sound/direct_sound_samples/08B05944.bin"

	.align 2
DirectSoundWaveData_08B1078C::
	.incbin "sound/direct_sound_samples/08B1078C.bin"

	.align 2
DirectSoundWaveData_08B13110::
	.incbin "sound/direct_sound_samples/08B13110.bin"

	.align 2
DirectSoundWaveData_08B16040::
	.incbin "sound/direct_sound_samples/08B16040.bin"

	.align 2
DirectSoundWaveData_08B18104::
	.incbin "sound/direct_sound_samples/08B18104.bin"

	.align 2
DirectSoundWaveData_08B1BD98::
	.incbin "sound/direct_sound_samples/08B1BD98.bin"

	.align 2
DirectSoundWaveData_08B1F954::
	.incbin "sound/direct_sound_samples/08B1F954.bin"

	.align 2
DirectSoundWaveData_08B2DDA8::
	.incbin "sound/direct_sound_samples/08B2DDA8.bin"

	.align 2
DirectSoundWaveData_08B30DBC::
	.incbin "sound/direct_sound_samples/08B30DBC.bin"

	.align 2
DirectSoundWaveData_08B34820::
	.incbin "sound/direct_sound_samples/08B34820.bin"

	.align 2
DirectSoundWaveData_08B3E248::
	.incbin "sound/direct_sound_samples/08B3E248.bin"

	.align 2
DirectSoundWaveData_08B3FD78::
	.incbin "sound/direct_sound_samples/08B3FD78.bin"

	.align 2
DirectSoundWaveData_08B40028::
	.incbin "sound/direct_sound_samples/08B40028.bin"

	.align 2
DirectSoundWaveData_08B41294::
	.incbin "sound/direct_sound_samples/08B41294.bin"

	.align 2
DirectSoundWaveData_08B41B78::
	.incbin "sound/direct_sound_samples/08B41B78.bin"

	.align 2
DirectSoundWaveData_08B43BA0::
	.incbin "sound/direct_sound_samples/08B43BA0.bin"

	.align 2
DirectSoundWaveData_08B4D3B4::
	.incbin "sound/direct_sound_samples/08B4D3B4.bin"

	.align 2
DirectSoundWaveData_08B527CC::
	.incbin "sound/direct_sound_samples/08B527CC.bin"

	.align 2
DirectSoundWaveData_08B5540C::
	.incbin "sound/direct_sound_samples/08B5540C.bin"

	.align 2
DirectSoundWaveData_08B57FD4::
	.incbin "sound/direct_sound_samples/08B57FD4.bin"

	.align 2
DirectSoundWaveData_08B5C47C::
	.incbin "sound/direct_sound_samples/08B5C47C.bin"

	.align 2
DirectSoundWaveData_08B6B2D8::
	.incbin "sound/direct_sound_samples/08B6B2D8.bin"

	.align 2
DirectSoundWaveData_08B6CE38::
	.incbin "sound/direct_sound_samples/08B6CE38.bin"

	.align 2
DirectSoundWaveData_08B6E7AC::
	.incbin "sound/direct_sound_samples/08B6E7AC.bin"

	.align 2
DirectSoundWaveData_08B70754::
	.incbin "sound/direct_sound_samples/08B70754.bin"

	.align 2
DirectSoundWaveData_08B766A8::
	.incbin "sound/direct_sound_samples/08B766A8.bin"

	.align 2
DirectSoundWaveData_08B77944::
	.incbin "sound/direct_sound_samples/08B77944.bin"

	.align 2
DirectSoundWaveData_08B7D0C0::
	.incbin "sound/direct_sound_samples/08B7D0C0.bin"

	.align 2
DirectSoundWaveData_08B7E6BC::
	.incbin "sound/direct_sound_samples/08B7E6BC.bin"

	.align 2
DirectSoundWaveData_08B84888::
	.incbin "sound/direct_sound_samples/08B84888.bin"

	.align 2
DirectSoundWaveData_08B85018::
	.incbin "sound/direct_sound_samples/08B85018.bin"

	.align 2
DirectSoundWaveData_08B85BBC::
	.incbin "sound/direct_sound_samples/08B85BBC.bin"

	.align 2
DirectSoundWaveData_08B88288::
	.incbin "sound/direct_sound_samples/08B88288.bin"

	.align 2
DirectSoundWaveData_08B88B88::
	.incbin "sound/direct_sound_samples/08B88B88.bin"

	.align 2
DirectSoundWaveData_08B894F0::
	.incbin "sound/direct_sound_samples/08B894F0.bin"

	.align 2
DirectSoundWaveData_08B89F0C::
	.incbin "sound/direct_sound_samples/08B89F0C.bin"

	.align 2
DirectSoundWaveData_08B8FB24::
	.incbin "sound/direct_sound_samples/08B8FB24.bin"

	.align 2
DirectSoundWaveData_08B94AC0::
	.incbin "sound/direct_sound_samples/08B94AC0.bin"

	.align 2
DirectSoundWaveData_08B99140::
	.incbin "sound/direct_sound_samples/08B99140.bin"

	.align 2
DirectSoundWaveData_08B9A0A0::
	.incbin "sound/direct_sound_samples/08B9A0A0.bin"

	.align 2
DirectSoundWaveData_08B9CAB4::
	.incbin "sound/direct_sound_samples/08B9CAB4.bin"

	.align 2
DirectSoundWaveData_08B9F7F8::
	.incbin "sound/direct_sound_samples/08B9F7F8.bin"

	.align 2
DirectSoundWaveData_08BA13C4::
	.incbin "sound/direct_sound_samples/08BA13C4.bin"

	.align 2
DirectSoundWaveData_08BA2EB8::
	.incbin "sound/direct_sound_samples/08BA2EB8.bin"

	.align 2
DirectSoundWaveData_08BA4674::
	.incbin "sound/direct_sound_samples/08BA4674.bin"

	.align 2
DirectSoundWaveData_08BA5DE8::
	.incbin "sound/direct_sound_samples/08BA5DE8.bin"

	.align 2
DirectSoundWaveData_08BA951C::
	.incbin "sound/direct_sound_samples/08BA951C.bin"

	.align 2
DirectSoundWaveData_08BAA088::
	.incbin "sound/direct_sound_samples/08BAA088.bin"

	.align 2
DirectSoundWaveData_08BAD418::
	.incbin "sound/direct_sound_samples/08BAD418.bin"

	.align 2
DirectSoundWaveData_08BB1AD0::
	.incbin "sound/direct_sound_samples/08BB1AD0.bin"

	.align 2
DirectSoundWaveData_08BB6CC4::
	.incbin "sound/direct_sound_samples/08BB6CC4.bin"

	.align 2
DirectSoundWaveData_08BB8CE0::
	.incbin "sound/direct_sound_samples/08BB8CE0.bin"

	.align 2
DirectSoundWaveData_08BB8D94::
	.incbin "sound/direct_sound_samples/08BB8D94.bin"

	.align 2
DirectSoundWaveData_08BBF3EC::
	.incbin "sound/direct_sound_samples/08BBF3EC.bin"

	.align 2
DirectSoundWaveData_08BC04D4::
	.incbin "sound/direct_sound_samples/08BC04D4.bin"
