	.align 2
ProgrammableWaveData_08120DAC::
	.incbin "sound/programmable_wave_samples/08120DAC.pcm"

ProgrammableWaveData_08120DBC::
	.incbin "sound/programmable_wave_samples/08120DBC.pcm"

ProgrammableWaveData_08120DCC::
	.incbin "sound/programmable_wave_samples/08120DCC.pcm"

ProgrammableWaveData_08120DDC::
	.incbin "sound/programmable_wave_samples/08120DDC.pcm"

ProgrammableWaveData_08120DEC::
	.incbin "sound/programmable_wave_samples/08120DEC.pcm"

ProgrammableWaveData_08120DFC::
	.incbin "sound/programmable_wave_samples/08120DFC.pcm"

ProgrammableWaveData_08120E0C::
	.incbin "sound/programmable_wave_samples/08120E0C.pcm"
