	.syntax unified
init__14MonsterFactory:
	push {r4, r5, lr}
	movs r4, #0
_08063AD4:
	lsls r0, r4, #0x10
	lsrs r0, r0, #0x10
	ldr r1, _08063D88
	bl put__14MonsterFactoryUsUs_Pv
	adds r4, #1
	cmp r4, #0xff
	bls _08063AD4
	ldr r1, _08063D8C
	movs r0, #1
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063D90
	movs r0, #5
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063D94
	movs r0, #0x32
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063D98
	movs r0, #0x31
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063D9C
	movs r0, #0x37
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063DA0
	movs r0, #0x33
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063DA4
	movs r0, #0x41
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063DA8
	movs r0, #0x42
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063DAC
	movs r0, #2
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063DB0
	movs r0, #4
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063DB4
	movs r0, #3
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063DB8
	movs r0, #0x4a
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063DBC
	movs r0, #0x52
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063DC0
	movs r0, #0x5a
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063DC4
	movs r0, #0x5b
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063DC8
	movs r0, #0x95
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063DCC
	movs r0, #6
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063DD0
	movs r0, #0x60
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063DD4
	movs r0, #0x62
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063DD8
	movs r0, #0x6f
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063DDC
	movs r0, #0x69
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063DE0
	movs r0, #0x3a
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063DE4
	movs r0, #0x9b
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063DE8
	movs r0, #0x9c
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063DEC
	movs r0, #0x10
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063DF0
	movs r0, #0x75
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063DF4
	movs r0, #0x7f
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063DF8
	movs r0, #0xe
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063DFC
	movs r0, #0xf
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063E00
	movs r0, #0x25
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063E04
	movs r0, #0x86
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063E08
	movs r0, #0xa2
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063E0C
	movs r0, #0x83
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063E10
	movs r0, #0xa4
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063E14
	movs r0, #0xa3
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063E18
	movs r0, #0x7c
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063E1C
	movs r0, #7
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063E20
	movs r0, #0x76
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063E24
	movs r0, #0x7d
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063E28
	movs r0, #0xac
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063E2C
	movs r0, #0x39
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063E30
	movs r0, #0x38
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063E34
	movs r0, #0x8e
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063E38
	movs r0, #0x21
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063E3C
	movs r0, #0x23
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063E40
	movs r0, #0x46
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063E44
	movs r0, #0x16
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063E48
	movs r0, #0xad
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063E4C
	movs r0, #0x90
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063E50
	movs r0, #0xae
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063E54
	movs r0, #0x65
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063E58
	movs r0, #0x5c
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063E5C
	movs r0, #9
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063E60
	movs r0, #0x7a
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063E64
	movs r0, #0x17
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063E68
	movs r0, #0xb6
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063E6C
	movs r0, #0x85
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063E70
	movs r0, #0x72
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063E74
	movs r0, #0x54
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063E78
	movs r0, #0xa6
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063E7C
	movs r0, #0x19
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063E80
	movs r0, #0xd
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063E84
	movs r0, #0x1c
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063E88
	movs r0, #0xaa
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063E8C
	movs r0, #0x87
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063E90
	movs r0, #0xb7
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063E94
	movs r0, #0xab
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063E98
	movs r0, #0xc
	bl put__14MonsterFactoryUsUs_Pv
	ldr r4, _08063E9C
	movs r0, #0x2e
	adds r1, r4, #0
	bl put__14MonsterFactoryUsUs_Pv
	movs r0, #0x2e
	adds r1, r4, #0
	bl put__14MonsterFactoryUsUs_Pv
	movs r0, #0x13
	adds r1, r4, #0
	bl put__14MonsterFactoryUsUs_Pv
	movs r0, #0x1a
	adds r1, r4, #0
	bl put__14MonsterFactoryUsUs_Pv
	movs r0, #0xbb
	adds r1, r4, #0
	bl put__14MonsterFactoryUsUs_Pv
	movs r0, #0xbc
	adds r1, r4, #0
	bl put__14MonsterFactoryUsUs_Pv
	ldr r5, _08063EA0
	movs r0, #0xa9
	adds r1, r5, #0
	bl put__14MonsterFactoryUsUs_Pv
	movs r0, #0x91
	adds r1, r5, #0
	bl put__14MonsterFactoryUsUs_Pv
	movs r0, #0x1b
	adds r1, r4, #0
	bl put__14MonsterFactoryUsUs_Pv
	movs r0, #0xb4
	adds r1, r4, #0
	bl put__14MonsterFactoryUsUs_Pv
	movs r0, #0xb5
	adds r1, r4, #0
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063EA4
	movs r0, #0xb
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063EA8
	movs r0, #0x11
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063EAC
	movs r0, #0xbd
	bl put__14MonsterFactoryUsUs_Pv
	ldr r1, _08063EB0
	movs r0, #0xbe
	bl put__14MonsterFactoryUsUs_Pv
	pop {r4, r5}
	pop {r0}
	bx r0
	.align 2, 0
_08063D88: .4byte create__21DefaultMonsterFactoryUsUs
_08063D8C: .4byte create__29ReconstructedCaribouFactoryUsUs
_08063D90: .4byte create__17MechaDragoFactoryUsUs
_08063D94: .4byte create__22BakedYammonsterFactoryUsUs
_08063D98: .4byte create__19SootDumplingFactoryUsUs
_08063D9C: .4byte create__16PotatoBugFactoryUsUs
_08063DA0: .4byte create__20WalkingBushieFactoryUsUs
_08063DA4: .4byte create__19BaldingEagleFactoryUsUs
_08063DA8: .4byte create__11TreeFactoryUsUs
_08063DAC: .4byte create__16MrPassionFactoryUsUs
_08063DB0: .4byte create__14ClaymanFactoryUsUs
_08063DB4: .4byte create__16OhSoSnakeFactoryUsUs
_08063DB8: .4byte create__18MobileGraveFactoryUsUs
_08063DBC: .4byte create__15ArachnidFactoryUsUs
_08063DC0: .4byte create__19RockingGhostFactoryUsUs
_08063DC4: .4byte create__15PseudoorFactoryUsUs
_08063DC8: .4byte create__18PorkSoldierFactoryUsUs
_08063DCC: .4byte create__15PorkTankFactoryUsUs
_08063DD0: .4byte create__17SandLizardFactoryUsUs
_08063DD4: .4byte create__17StickyGlopFactoryUsUs
_08063DD8: .4byte create__18CattlesnakeFactoryUsUs
_08063DDC: .4byte create__15PigtuniaFactoryUsUs
_08063DE0: .4byte create__17StickySlugFactoryUsUs
_08063DE4: .4byte create__20WailingGuitarFactoryUsUs
_08063DE8: .4byte create__17BeatenDrumFactoryUsUs
_08063DEC: .4byte create__18JealousBassFactoryUsUs
_08063DF0: .4byte create__18MechaTurtleFactoryUsUs
_08063DF4: .4byte create__18WoundupBearFactoryUsUs
_08063DF8: .4byte create__27WomanizingPigMask1stFactoryUsUs
_08063DFC: .4byte create__27WomanizingPigMask2ndFactoryUsUs
_08063E00: .4byte create__16BarricadeFactoryUsUs
_08063E04: .4byte create__18AtomicRobotFactoryUsUs
_08063E08: .4byte create__18SadJunkHeapFactoryUsUs
_08063E0C: .4byte create__16MinorRoboFactoryUsUs
_08063E10: .4byte create__17BatteryManFactoryUsUs
_08063E14: .4byte create__18SurpriseBoxFactoryUsUs
_08063E18: .4byte create__18MissMarshmallowFactoryUsUs
_08063E1C: .4byte create__16MrGenetorFactoryUsUs
_08063E20: .4byte create__14BroTeamFactoryUsUs
_08063E24: .4byte create__22AlmostMechaLionFactoryUsUs
_08063E28: .4byte create__20PorkCommanderFactoryUsUs
_08063E2C: .4byte create__16ChillyDogFactoryUsUs
_08063E30: .4byte create__16TenYetiFactoryUsUs
_08063E34: .4byte create__19SteelGorillaFactoryUsUs
_08063E38: .4byte create__17ScaredyBotFactoryUsUs
_08063E3C: .4byte create__15BlazeflyFactoryUsUs
_08063E40: .4byte create__14HotheadFactoryUsUs
_08063E44: .4byte create__16NewFassadFactoryUsUs
_08063E48: .4byte create__17NavySquealFactoryUsUs
_08063E4C: .4byte create__17FishRoeManFactoryUsUs
_08063E50: .4byte create__17MasterEddyFactoryUsUs
_08063E54: .4byte create__19ZombieshroomFactoryUsUs
_08063E58: .4byte create__20EerieSmile3rdFactoryUsUs
_08063E5C: .4byte create__20EerieSmile1stFactoryUsUs
_08063E60: .4byte create__16MonkalrusFactoryUsUs
_08063E64: .4byte create__20EerieSmile2ndFactoryUsUs
_08063E68: .4byte create__15TitanianFactoryUsUs
_08063E6C: .4byte create__20EerieSmile4thFactoryUsUs
_08063E70: .4byte create__16DragonflyFactoryUsUs
_08063E74: .4byte create__18BarrierTrioFactoryUsUs
_08063E78: .4byte create__16HuggyBombFactoryUsUs
_08063E7C: .4byte create__14TLCTreeFactoryUsUs
_08063E80: .4byte create__19MaskedMan1stFactoryUsUs
_08063E84: .4byte create__20MiracleFassadFactoryUsUs
_08063E88: .4byte create__21PorkLieutenantFactoryUsUs
_08063E8C: .4byte create__19NuclearRobotFactoryUsUs
_08063E90: .4byte create__19UpgradedRoboFactoryUsUs
_08063E94: .4byte create__21PorkColonel2ndFactoryUsUs
_08063E98: .4byte create__26NaturalKillerCyborgFactoryUsUs
_08063E9C: .4byte create__17MechaPorkyFactoryUsUs
_08063EA0: .4byte create__21MechaPorky0607FactoryUsUs
_08063EA4: .4byte create__12PorkyFactoryUsUs
_08063EA8: .4byte create__28AbsolutelySafeCapsuleFactoryUsUs
_08063EAC: .4byte create__28MaskedMan2ndFactoryUsUs
_08063EB0: .4byte create__28MaskedMan3rdFactoryUsUs
	.syntax divided
